Add monthly report for march 2022
Rust-GCC/Reporting pull request #21
Opened 2022-03-30 10:27 UTC by philberty

WIP

2022-03-30 11:47 UTC, dkm requested changes

2022-03-31 07:13 UTC, CohenArthur commented on 2022-03-monthly-report.org
> +- Enforce quites during command line cfg arguments [[https://github.com/Rust-GCC/gccrs/pull/983][PR983]]
```suggestion
- Enforce quotes during command line cfg arguments [[https://github.com/Rust-GCC/gccrs/pull/983][PR983]]
```

2022-03-31 07:13 UTC, CohenArthur commented on 2022-03-monthly-report.org
> +*** Recursive macros using seperators
```suggestion
*** Recursive macros using separators
```

2022-03-31 07:13 UTC, CohenArthur commented on 2022-03-monthly-report.org
> +*** Implement proper repetition separators
This section is actually similar to the previous one, I think we should keep only one of the two

2022-04-04 10:51 UTC, merged